# Dependencies
markdown: kramdown

kramdown:
  input: GFM

pygments: false

# Permalinks
permalink: '/announcements/:title'

# Setup
title: OxyPlot
description: 'A cross-platform plotting library for .NET'
url: https://oxyplot.github.io

author:
  name: 'OxyPlot'
  url: https://oxyplot.github.io

paginate: 5
paginate_path: '/announcements/:num'

# Custom vars
version: 2015.1
docs: https://oxyplot.readthedocs.io/en/latest/
forum: https://oxyplot.userecho.com/
nuget: https://www.nuget.org/packages?q=oxyplot
myget: https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Core
examples: https://github.com/oxyplot/oxyplot/tree/develop/Source/Examples/
twitter: https://twitter.com/search?q=oxyplot
stackOverflow: https://stackoverflow.com/questions/tagged/oxyplot?sort=newest
chat: https://gitter.im/oxyplot/oxyplot

github:
  repo: https://github.com/oxyplot/oxyplot/
